const FONT_AWESOME_ICONS = [
    "solid/address-book", "regular/address-book", "solid/address-card", "regular/address-card", "solid/align-center",
    "regular/align-center", "solid/align-justify", "regular/align-justify", "solid/align-left", "regular/align-left",
    "solid/align-right", "regular/align-right", "solid/anchor", "regular/anchor", "solid/angle-double-down",
    "regular/angle-double-down", "solid/angle-double-left", "regular/angle-double-left", "solid/angle-double-right",
    "regular/angle-double-right", "solid/angle-double-up", "regular/angle-double-up", "solid/angle-down",
    "regular/angle-down", "solid/angle-left", "regular/angle-left", "solid/angle-right", "regular/angle-right",
    "solid/angle-up", "regular/angle-up", "solid/archive", "regular/archive", "solid/arrow-alt-circle-down",
    "regular/arrow-alt-circle-down", "solid/arrow-alt-circle-left", "regular/arrow-alt-circle-left",
    "solid/arrow-alt-circle-right", "regular/arrow-alt-circle-right", "solid/arrow-alt-circle-up",
    "regular/arrow-alt-circle-up", "solid/arrow-down", "regular/arrow-down", "solid/arrow-left", "regular/arrow-left",
    "solid/arrow-right", "regular/arrow-right", "solid/arrow-up", "regular/arrow-up", "solid/asterisk",
    "regular/asterisk", "solid/at", "regular/at", "solid/award", "regular/award", "solid/ban", "regular/ban",
    "solid/barcode", "regular/barcode", "solid/bars", "regular/bars", "solid/battery-empty", "regular/battery-empty",
    "solid/battery-full", "regular/battery-full", "solid/battery-half", "regular/battery-half",
    "solid/battery-quarter", "regular/battery-quarter", "solid/battery-three-quarters",
    "regular/battery-three-quarters", "solid/bed", "regular/bed", "solid/beer", "regular/beer", "solid/bell",
    "regular/bell", "solid/bell-slash", "regular/bell-slash", "solid/bicycle", "regular/bicycle", "solid/binoculars",
    "regular/binoculars", "solid/birthday-cake", "regular/birthday-cake", "solid/bolt", "regular/bolt", "solid/bomb",
    "regular/bomb", "solid/book", "regular/book", "solid/book-open", "regular/book-open", "solid/bookmark",
    "regular/bookmark", "solid/box", "regular/box", "solid/box-open", "regular/box-open", "solid/boxes",
    "regular/boxes", "solid/briefcase", "regular/briefcase", "solid/bug", "regular/bug", "solid/building",
    "regular/building", "solid/bullhorn", "regular/bullhorn", "solid/bullseye", "regular/bullseye", "solid/bus",
    "regular/bus", "solid/calculator", "regular/calculator", "solid/calendar", "regular/calendar",
    "solid/calendar-alt", "regular/calendar-alt", "solid/calendar-check", "regular/calendar-check",
    "solid/calendar-minus", "regular/calendar-minus", "solid/calendar-plus", "regular/calendar-plus",
    "solid/calendar-times", "regular/calendar-times", "solid/camera", "regular/camera", "solid/camera-retro",
    "regular/camera-retro", "solid/car", "regular/car", "solid/caret-down", "regular/caret-down", "solid/caret-left",
    "regular/caret-left", "solid/caret-right", "regular/caret-right", "solid/caret-up", "regular/caret-up",
    "solid/cart-arrow-down", "regular/cart-arrow-down", "solid/cart-plus", "regular/cart-plus", "solid/certificate",
    "regular/certificate", "solid/chart-area", "regular/chart-area", "solid/chart-bar", "regular/chart-bar",
    "solid/chart-line", "regular/chart-line", "solid/chart-pie", "regular/chart-pie", "solid/check", "regular/check",
    "solid/check-circle", "regular/check-circle", "solid/check-double", "regular/check-double", "solid/check-square",
    "regular/check-square", "solid/chevron-circle-down", "regular/chevron-circle-down", "solid/chevron-circle-left",
    "regular/chevron-circle-left", "solid/chevron-circle-right", "regular/chevron-circle-right",
    "solid/chevron-circle-up", "regular/chevron-circle-up", "solid/chevron-down", "regular/chevron-down",
    "solid/chevron-left", "regular/chevron-left", "solid/chevron-right", "regular/chevron-right", "solid/chevron-up",
    "regular/chevron-up", "solid/circle", "regular/circle", "solid/clipboard", "regular/clipboard",
    "solid/clipboard-check", "regular/clipboard-check", "solid/clipboard-list", "regular/clipboard-list",
    "solid/clock", "regular/clock", "solid/clone", "regular/clone", "solid/cloud", "regular/cloud",
    "solid/cloud-download-alt", "regular/cloud-download-alt", "solid/cloud-upload-alt", "regular/cloud-upload-alt",
    "solid/code", "regular/code", "solid/code-branch", "regular/code-branch", "solid/coffee", "regular/coffee",
    "solid/cog", "regular/cog", "solid/cogs", "regular/cogs", "solid/columns", "regular/columns", "solid/comment",
    "regular/comment", "solid/comment-alt", "regular/comment-alt", "solid/comment-dots", "regular/comment-dots",
    "solid/comment-slash", "regular/comment-slash", "solid/comments", "regular/comments", "solid/compass",
    "regular/compass", "solid/compress", "regular/compress", "solid/compress-arrows-alt",
    "regular/compress-arrows-alt", "solid/copy", "regular/copy", "solid/credit-card", "regular/credit-card",
    "solid/crop", "regular/crop", "solid/crosshairs", "regular/crosshairs", "solid/cube", "regular/cube",
    "solid/cubes", "regular/cubes", "solid/cut", "regular/cut", "solid/database", "regular/database", "solid/desktop",
    "regular/desktop", "solid/download", "regular/download", "solid/edit", "regular/edit", "solid/eject",
    "regular/eject", "solid/ellipsis-h", "regular/ellipsis-h", "solid/ellipsis-v", "regular/ellipsis-v",
    "solid/envelope", "regular/envelope", "solid/envelope-open", "regular/envelope-open", "solid/envelope-square",
    "regular/envelope-square", "solid/eraser", "regular/eraser", "solid/exchange-alt", "regular/exchange-alt",
    "solid/exclamation", "regular/exclamation", "solid/exclamation-circle", "regular/exclamation-circle",
    "solid/exclamation-triangle", "regular/exclamation-triangle", "solid/expand", "regular/expand",
    "solid/expand-arrows-alt", "regular/expand-arrows-alt", "solid/external-link-alt", "regular/external-link-alt",
    "solid/external-link-square-alt", "regular/external-link-square-alt", "solid/eye", "regular/eye",
    "solid/eye-dropper", "regular/eye-dropper", "solid/eye-slash", "regular/eye-slash", "solid/fast-backward",
    "regular/fast-backward", "solid/fast-forward", "regular/fast-forward", "solid/fax", "regular/fax", "solid/file",
    "regular/file", "solid/file-alt", "regular/file-alt", "solid/file-archive", "regular/file-archive",
    "solid/file-audio", "regular/file-audio", "solid/file-code", "regular/file-code", "solid/file-excel",
    "regular/file-excel", "solid/file-image", "regular/file-image", "solid/file-pdf", "regular/file-pdf",
    "solid/file-powerpoint", "regular/file-powerpoint", "solid/file-video", "regular/file-video", "solid/file-word",
    "regular/file-word", "solid/film", "regular/film", "solid/filter", "regular/filter", "solid/fire", "regular/fire",
    "solid/fire-extinguisher", "regular/fire-extinguisher", "solid/flag", "regular/flag", "solid/flag-checkered",
    "regular/flag-checkered", "solid/flask", "regular/flask", "solid/folder", "regular/folder", "solid/folder-open",
    "regular/folder-open", "solid/font", "regular/font", "solid/forward", "regular/forward", "solid/frown",
    "regular/frown", "solid/gamepad", "regular/gamepad", "solid/gavel", "regular/gavel", "solid/gem", "regular/gem",
    "solid/genderless", "regular/genderless", "solid/gift", "regular/gift", "solid/glass-martini",
    "regular/glass-martini", "solid/globe", "regular/globe", "solid/graduation-cap", "regular/graduation-cap",
    "solid/h-square", "regular/h-square", "solid/hashtag", "regular/hashtag", "solid/hdd", "regular/hdd",
    "solid/heading", "regular/heading", "solid/headphones", "regular/headphones", "solid/heart", "regular/heart",
    "solid/heartbeat", "regular/heartbeat", "solid/history", "regular/history", "solid/home", "regular/home",
    "solid/hospital", "regular/hospital", "solid/hourglass", "regular/hourglass", "solid/hourglass-end",
    "regular/hourglass-end", "solid/hourglass-half", "regular/hourglass-half", "solid/hourglass-start",
    "regular/hourglass-start", "solid/i-cursor", "regular/i-cursor", "solid/id-badge", "regular/id-badge",
    "solid/id-card", "regular/id-card", "solid/image", "regular/image", "solid/images", "regular/images",
    "solid/inbox", "regular/inbox", "solid/indent", "regular/indent", "solid/industry", "regular/industry",
    "solid/info", "regular/info", "solid/info-circle", "regular/info-circle", "solid/key", "regular/key",
    "solid/keyboard", "regular/keyboard", "solid/language", "regular/language", "solid/laptop", "regular/laptop",
    "solid/leaf", "regular/leaf", "solid/lemon", "regular/lemon", "solid/level-down-alt", "regular/level-down-alt",
    "solid/level-up-alt", "regular/level-up-alt", "solid/life-ring", "regular/life-ring", "solid/lightbulb",
    "regular/lightbulb", "solid/link", "regular/link", "solid/lira-sign", "regular/lira-sign", "solid/list",
    "regular/list", "solid/list-alt", "regular/list-alt", "solid/list-ol", "regular/list-ol", "solid/list-ul",
    "regular/list-ul", "solid/location-arrow", "regular/location-arrow", "solid/lock", "regular/lock",
    "solid/lock-open", "regular/lock-open", "solid/magic", "regular/magic", "solid/magnet", "regular/magnet",
    "solid/map", "regular/map", "solid/map-marker", "regular/map-marker", "solid/map-marker-alt",
    "regular/map-marker-alt", "solid/map-pin", "regular/map-pin", "solid/map-signs", "regular/map-signs", "solid/mars",
    "regular/mars", "solid/mercury", "regular/mercury", "solid/microchip", "regular/microchip", "solid/microphone",
    "regular/microphone", "solid/microphone-slash", "regular/microphone-slash", "solid/minus", "regular/minus",
    "solid/minus-circle", "regular/minus-circle", "solid/minus-square", "regular/minus-square", "solid/mobile",
    "regular/mobile", "solid/mobile-alt", "regular/mobile-alt", "solid/money-bill-alt", "regular/money-bill-alt",
    "solid/moon", "regular/moon", "solid/motorcycle", "regular/motorcycle", "solid/mouse-pointer",
    "regular/mouse-pointer", "solid/music", "regular/music", "solid/neuter", "regular/neuter", "solid/newspaper",
    "regular/newspaper", "solid/object-group", "regular/object-group", "solid/object-ungroup",
    "regular/object-ungroup", "solid/outdent", "regular/outdent", "solid/paint-brush", "regular/paint-brush",
    "solid/paper-plane", "regular/paper-plane", "solid/paperclip", "regular/paperclip", "solid/paragraph",
    "regular/paragraph", "solid/paste", "regular/paste", "solid/pause", "regular/pause", "solid/pause-circle",
    "regular/pause-circle", "solid/paw", "regular/paw", "solid/pen-square", "regular/pen-square", "solid/pencil-alt",
    "regular/pencil-alt", "solid/percent", "regular/percent", "solid/phone", "regular/phone", "solid/phone-slash",
    "regular/phone-slash", "solid/phone-square", "regular/phone-square", "solid/phone-volume", "regular/phone-volume",
    "solid/plane", "regular/plane", "solid/play", "regular/play", "solid/play-circle", "regular/play-circle",
    "solid/plug", "regular/plug", "solid/plus", "regular/plus", "solid/plus-circle", "regular/plus-circle",
    "solid/plus-square", "regular/plus-square", "solid/podcast", "regular/podcast", "solid/power-off",
    "regular/power-off", "solid/print", "regular/print", "solid/puzzle-piece", "regular/puzzle-piece", "solid/qrcode",
    "regular/qrcode", "solid/question", "regular/question", "solid/question-circle", "regular/question-circle",
    "solid/quote-left", "regular/quote-left", "solid/quote-right", "regular/quote-right", "solid/random",
    "regular/random", "solid/recycle", "regular/recycle", "solid/redo", "regular/redo", "solid/redo-alt",
    "regular/redo-alt", "solid/registered", "regular/registered", "solid/reply", "regular/reply", "solid/reply-all",
    "regular/reply-all", "solid/retweet", "regular/retweet", "solid/road", "regular/road", "solid/rocket",
    "regular/rocket", "solid/rss", "regular/rss", "solid/rss-square", "regular/rss-square", "solid/ruble-sign",
    "regular/ruble-sign", "solid/rupee-sign", "regular/rupee-sign", "solid/save", "regular/save", "solid/search",
    "regular/search", "solid/search-minus", "regular/search-minus", "solid/search-plus", "regular/search-plus",
    "solid/server", "regular/server", "solid/share", "regular/share", "solid/share-alt", "regular/share-alt",
    "solid/share-alt-square", "regular/share-alt-square", "solid/share-square", "regular/share-square",
    "solid/shekel-sign", "regular/shekel-sign", "solid/shield-alt", "regular/shield-alt", "solid/ship", "regular/ship",
    "solid/shopping-bag", "regular/shopping-bag", "solid/shopping-basket", "regular/shopping-basket",
    "solid/shopping-cart", "regular/shopping-cart", "solid/shower", "regular/shower", "solid/sign-in-alt",
    "regular/sign-in-alt", "solid/sign-out-alt", "regular/sign-out-alt", "solid/signal", "regular/signal",
    "solid/sitemap", "regular/sitemap", "solid/sliders-h", "regular/sliders-h", "solid/smile", "regular/smile",
    "solid/sort", "regular/sort", "solid/sort-alpha-down", "regular/sort-alpha-down", "solid/sort-alpha-up",
    "regular/sort-alpha-up", "solid/sort-amount-down", "regular/sort-amount-down", "solid/sort-amount-up",
    "regular/sort-amount-up", "solid/sort-down", "regular/sort-down", "solid/sort-numeric-down",
    "regular/sort-numeric-down", "solid/sort-numeric-up", "regular/sort-numeric-up", "solid/sort-up",
    "regular/sort-up", "solid/space-shuttle", "regular/space-shuttle", "solid/spinner", "regular/spinner",
    "solid/square", "regular/square", "solid/star", "regular/star", "solid/star-half", "regular/star-half",
    "solid/step-backward", "regular/step-backward", "solid/step-forward", "regular/step-forward", "solid/stethoscope",
    "regular/stethoscope", "solid/sticky-note", "regular/sticky-note", "solid/stop", "regular/stop",
    "solid/stop-circle", "regular/stop-circle", "solid/stopwatch", "regular/stopwatch", "solid/street-view",
    "regular/street-view", "solid/strikethrough", "regular/strikethrough", "solid/subscript", "regular/subscript",
    "solid/subway", "regular/subway", "solid/suitcase", "regular/suitcase", "solid/sun", "regular/sun",
    "solid/superscript", "regular/superscript", "solid/sync", "regular/sync", "solid/sync-alt", "regular/sync-alt",
    "solid/syringe", "regular/syringe", "solid/table", "regular/table", "solid/tablet", "regular/tablet",
    "solid/tablet-alt", "regular/tablet-alt", "solid/tachometer-alt", "regular/tachometer-alt", "solid/tag",
    "regular/tag", "solid/tags", "regular/tags", "solid/tasks", "regular/tasks", "solid/taxi", "regular/taxi",
    "solid/terminal", "regular/terminal", "solid/text-height", "regular/text-height", "solid/text-width",
    "regular/text-width", "solid/th", "regular/th", "solid/th-large", "regular/th-large", "solid/th-list",
    "regular/th-list", "solid/thermometer-empty", "regular/thermometer-empty", "solid/thermometer-full",
    "regular/thermometer-full", "solid/thermometer-half", "regular/thermometer-half", "solid/thermometer-quarter",
    "regular/thermometer-quarter", "solid/thermometer-three-quarters", "regular/thermometer-three-quarters",
    "solid/thumbs-down", "regular/thumbs-down", "solid/thumbs-up", "regular/thumbs-up", "solid/thumbtack",
    "regular/thumbtack", "solid/ticket-alt", "regular/ticket-alt", "solid/times", "regular/times",
    "solid/times-circle", "regular/times-circle", "solid/tint", "regular/tint", "solid/toggle-off",
    "regular/toggle-off", "solid/toggle-on", "regular/toggle-on", "solid/trademark", "regular/trademark",
    "solid/train", "regular/train", "solid/transgender", "regular/transgender", "solid/transgender-alt",
    "regular/transgender-alt", "solid/trash", "regular/trash", "solid/trash-alt", "regular/trash-alt", "solid/tree",
    "regular/tree", "solid/trophy", "regular/trophy", "solid/truck", "regular/truck", "solid/tty", "regular/tty",
    "solid/tv", "regular/tv", "solid/umbrella", "regular/umbrella", "solid/underline", "regular/underline",
    "solid/undo", "regular/undo", "solid/undo-alt", "regular/undo-alt", "solid/universal-access",
    "regular/universal-access", "solid/university", "regular/university", "solid/unlock", "regular/unlock",
    "solid/unlock-alt", "regular/unlock-alt", "solid/upload", "regular/upload", "solid/user", "regular/user",
    "solid/user-circle", "regular/user-circle", "solid/user-md", "regular/user-md", "solid/user-plus",
    "regular/user-plus", "solid/user-secret", "regular/user-secret", "solid/user-times", "regular/user-times",
    "solid/users", "regular/users", "solid/utensil-spoon", "regular/utensil-spoon", "solid/utensils",
    "regular/utensils", "solid/venus", "regular/venus", "solid/venus-double", "regular/venus-double",
    "solid/venus-mars", "regular/venus-mars", "solid/video", "regular/video", "solid/video-slash",
    "regular/video-slash", "solid/volume-down", "regular/volume-down", "solid/volume-off", "regular/volume-off",
    "solid/volume-up", "regular/volume-up", "solid/wheelchair", "regular/wheelchair", "solid/wifi", "regular/wifi",
    "solid/window-close", "regular/window-close", "solid/window-maximize", "regular/window-maximize",
    "solid/window-minimize", "regular/window-minimize", "solid/window-restore", "regular/window-restore",
    "solid/wrench", "regular/wrench", "solid/yen-sign", "regular/yen-sign", "brands/amazon", "brands/apple",
    "brands/android", "brands/windows", "brands/github", "brands/google", "brands/facebook", "brands/twitter",
    "brands/instagram", "brands/linkedin", "brands/youtube", "brands/whatsapp", "brands/telegram", "brands/spotify",
    "brands/twitch", "brands/discord", "brands/slack", "brands/paypal", "brands/stripe", "brands/bitcoin",
    "brands/aws", "brands/figma", "brands/dribbble", "brands/behance", "brands/pinterest", "brands/reddit",
    "brands/tiktok", "brands/vimeo", "brands/dropbox", "brands/salesforce", "brands/skype", "brands/steam",
    "brands/xbox", "brands/playstation",
];



